exclude: '.git/'
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
        additional_dependencies: ['click==8.0.4']
